Actor critic
reinforcement-learning-kr/reinforcement-learning-pytorch pull request #1
Opened 2018-10-04 19:14 UTC by dnddnjs

add actor-critic agent for cartpole

2018-10-08 09:20 UTC, keon requested changes
I added some comments. Comments are mostly about styles.
I couldn't review the algorithm in detail, so I'll comeback tomorrow to comment on the logic in detail.

2018-10-08 09:20 UTC, keon commented on 1-grid-world/1-policy-iteration/environment.py
> +UNIT = 100  # 픽셀 수
english

2018-10-08 09:20 UTC, keon commented on 2-cartpole/1-dqn/train.py
> +if __name__=="__main__":
we should wrap this function into something like `main()` and let `if __name__=="__main__"` call that function. 
variables and functions declared in this if __name__ == "__main__" is `global`

2018-10-08 09:20 UTC, keon commented on 2-cartpole/1-dqn/train.py
> +    net.apply(weights_init)
i think we can embed `weights_init` inside `Model` class and call it inside `__init__`.

2018-10-08 09:20 UTC, keon commented on 2-cartpole/1-dqn/train.py
> +from model import Model
Can we have a better name for `Model`?

2018-10-08 09:20 UTC, keon commented on 2-cartpole/2-actor-critic/main.py
> +    state = sample[0]
we can replace this with one-liner
```
state, action, reward, next_state, mask = sample
```

2018-10-08 09:20 UTC, keon commented on 2-cartpole/2-actor-critic/main.py
> +    pred = reward + mask * args.gamma * next_value[0]
what is the purpose of `mask`?

2018-10-08 09:20 UTC, keon commented on 2-cartpole/2-actor-critic/test.py
> +if __name__=="__main__":
same applies for every files.
we should use `main()` and call it here.

2018-10-08 09:20 UTC, keon commented on 2-cartpole/2-actor-critic/main.py
> +            sample = [state, action, reward, next_state, mask]
what would be a better name for `sample`?

2018-10-08 09:20 UTC, keon commented on 2-cartpole/2-actor-critic/main.py
> +    _, next_value = net(next_state)
this is one example of the problem of declaring things inside `if __name__ == '__main__'`.
`net` was declared below as a global variable and we are able to use it here, which may confuse reader.
net should be one of the arguments of this function.

2018-10-08 09:20 UTC, keon commented on 2-cartpole/2-actor-critic/train.py
> +    state = sample[0]
same one-liner change can apply here.

2018-10-08 09:20 UTC, keon commented on 2-cartpole/2-actor-critic/train.py
> +    _, next_value = net(next_state)
same problem as above

2018-10-08 09:20 UTC, keon commented on 2-cartpole/3-multi-step/train.py
> +        states, next_states, actions, rewards, masks = [], [], [], [], []
there seems to be multiple patterns used for storing memory.
There's Memory class for dqn, and here we store state, next_state, actions, and etc into separate lists.
We should consolidate the style.

2018-10-08 09:20 UTC, keon commented on 3-atari/1-dqn/train.py
> +    def weights_init(m):
this should be embedded into the model class as I commented for cartpole dqn

2018-10-08 09:20 UTC, keon commented on 3-atari/1-dqn/train.py
> +from utils import *
plz refrain from using import *.
it makes difficult to understand what comes from what.

2018-10-08 09:20 UTC, keon commented on 3-atari/1-dqn/train.py
> +    history = torch.stack(batch.history).cuda()
instead of `cuda`, we should use `to` function.

good pattern for this is:
```python
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu") # declare this at the top
t = t.to(DEVICE) # t is the torch tensor
```
this will automatically send t to "cuda" or "cpu" depending on the user's setting

2018-10-08 09:20 UTC, keon commented on 3-atari/1-dqn/train.py
> +            if action == 0:
`real_action = action + 1` ?

2018-10-08 09:20 UTC, keon commented on 3-atari/1-dqn/train.py
> +            if action == 0:
or better, add 1 inside `get_action`?

2018-10-09 03:11 UTC, dnddnjs commented on 2-cartpole/1-dqn/train.py
> +from model import Model
Then maybe qnet is better name for the model

2018-10-09 03:34 UTC, dnddnjs commented on 2-cartpole/2-actor-critic/main.py
> +            sample = [state, action, reward, next_state, mask]
Transition or transition_tuple would be replacement for the sample. Or I can feed the sample directly to the memory.push() method

2018-10-09 04:45 UTC, dnddnjs commented on 2-cartpole/2-actor-critic/main.py
> +    pred = reward + mask * args.gamma * next_value[0]
if the sample is from end of episode, then next_value has to be 0. mask is 0 if the sample is from end of episode

2018-10-09 07:18 UTC, keon approved these changes

2018-10-09 07:18 UTC, merged